### ISSUE TITLE
Image Generation

### ISSUE THREAD

**Issue by taeinkwon** [lucidrains/transfusion-pytorch#22] opened 2024-11-05 00:18 UTC
Hi

Using this code, I could sample text successfully ( model.sample()) but the image part is empty. Do you know how to sample (or generate) an image for the inference? It would be helpful if you could give me any pointers for this. Thank you!

**Comment by lucidrains** [comment] 2024-11-05 00:21
@taeinkwon hey Taein, thank you for your interest

did you train with both text and images before sampling?

**Comment by taeinkwon** [comment] 2024-11-05 00:57
Yes I trained with both text and images like the following:
```
text_and_images = [[text, image] for text, image in zip(tokens['input_ids'], imgs)]
loss = model(text_and_images)
```
Do you have an example for generating images?

**Comment by lucidrains** [comment] 2024-11-05 01:49
@taeinkwon could it be you included the `eos` id within your text? it needs to be placed after the image

**Comment by lucidrains** [comment] 2024-11-05 01:49
@taeinkwon let me debug it tomorrow morning with a toy example

**Comment by taeinkwon** [comment] 2024-11-05 10:13
<img width="615" alt="Screenshot 2024-11-04 at 17 07 56" src="https://github.com/user-attachments/assets/13705237-5a43-4689-b09b-ccd213039d78">
I am using BertTokenizer, and if I understand correctly, 101 is BOS and 102 is EOS which are included here.

**Comment by taeinkwon** [comment] 2024-11-05 11:12
I also replaced the BOS and EOS tokens as num_text_tokens and (num_text_tokens + 1) like written in 

[self.sos_id, self.eos_id = num_text_tokens, (num_text_tokens + 1)](https://github.com/lucidrains/transfusion-pytorch/blob/6059078adf8e22c0bce2c77ce9ea028e8b1dd4d4/transfusion_pytorch/transfusion.py#L1097C9-L1097C74)

but still the image output is None. Do you have any clues?

**Comment by lucidrains** [comment] 2024-11-05 13:27
how long are your sequences?

**Comment by taeinkwon** [comment] 2024-11-05 14:48
It's very short. A few words. Now, I have fixed the length to 16. 
I can't see any messages In the latest version.

What I found is that after training a few iterations, it can't generate images. However, when creating an initialized model, I can generate images with very small (ex., 8) num_text_tokens. I guess the training process breaks it?

I have attached my model FYI.
---------------------------------
def create_model(vocab_size, image_size):
    model = Transfusion(
        num_text_tokens=vocab_size,
        dim_latent=384,
        channel_first_latent=True,
        modality_default_shape=((image_size // 32, image_size // 32),),
        modality_encoder=torch.nn.Sequential(
            torch.nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1),
            torch.nn.ReLU(),
            torch.nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),
            torch.nn.ReLU(),
            torch.nn.Conv2d(128, 256, kernel_size=3, stride=2, padding=1),
            torch.nn.ReLU(),
            torch.nn.Conv2d(256, 384, kernel_size=3, stride=1, padding=1),
        ),
        modality_decoder=torch.nn.Sequential(
            torch.nn.ConvTranspose2d(384, 256, kernel_size=3, stride=2, padding=1, output_padding=1),
            torch.nn.ReLU(),
            torch.nn.ConvTranspose2d(256, 128, kernel_size=3, stride=2, padding=1, output_padding=1),
            torch.nn.ReLU(),
            torch.nn.ConvTranspose2d(128, 64, kernel_size=3, stride=2, padding=1, output_padding=1),
            torch.nn.ReLU(),
            torch.nn.Conv2d(64, 3, kernel_size=3, stride=1, padding=1),
            torch.nn.Sigmoid(),
        ),
        transformer=dict(
            dim=512,
            depth=8
        )
    )
    for param in model.parameters():
        param.requires_grad = True
    return model

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
# tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen2.5-0.5B-Instruct')
image_size = 256
model = create_model(vocab_size=tokenizer.vocab_size, image_size=image_size)

**Comment by lucidrains** [comment] 2024-11-05 14:50
@taeinkwon hey Taein, thank you for this, i will get a working demo using cifar-100 by end of today or tomorrow

this repository is being prioritized given [a new robotics work](https://www.physicalintelligence.company/blog/pi0) based on Transfusion

**Comment by taeinkwon** [comment] 2024-11-10 11:07
Hi @lucidrains, I wonder whether you have figured out why images are not generated. I also checked this one https://github.com/lucidrains/transfusion-pytorch/discussions/14, and this code also can not generate images FYI.  Thank you!

**Comment by lucidrains** [comment] 2024-11-10 14:44
@taeinkwon hey Taein, will take a look at this in the next few hours

thank you for your patience

**Comment by lucidrains** [comment] 2024-11-10 16:33
@taeinkwon hey Taein, i found the issue and it is resolved in 0.3.5

when i added the ability for the language model to produce the length of the modality, i did not update the offset, leading to erroneous masking in adaptive modules as well as the text label

you can try running `python train_toy.py` and it should overfit on a small contrived example

**Comment by lucidrains** [comment] 2024-11-12 16:04
@taeinkwon working?

**Comment by taeinkwon** [comment] 2024-11-12 16:57
Hi @lucidrains , I appreciate your update. I can check it this weekend. I will let you know whether it works or not by that time. Thank you!

**Comment by taeinkwon** [comment] 2024-11-15 21:25
Hi @lucidrains,

I trained image and text pairs for one hour. After that, the sample method only generates text without images. At least the text looks reasonable.
When I feed text to the model, I obtain an image that displays a grey color only. Somehow, training images do not work for me properly. I double-checked the inputs to the model, and the inputs look good to me. Do you have any ideas, or is there any place I need to check more? 

I have also attached what the generated image's values look like. 

<img width="623" alt="image" src="https://github.com/user-attachments/assets/d5c00038-0f68-4975-b2b1-73a07e8b7550">

**Comment by robertmash2** [comment] 2024-11-15 21:26
@taeinkwon, did you expand the pixel values back out to int8 0-255?

**Comment by lucidrains** [comment] 2024-11-15 21:34
@taeinkwon ah ok! so it is generating an image, but the image is grey, is that correct? I'll take another look tomorrow morning

**Comment by taeinkwon** [comment] 2024-11-15 21:48
More specifically, sampling does not work for images, and when I feed text, the image is grey. and yes I expanded the pixel values back out to int 8. Thank you for your investigation!

**Comment by lucidrains** [comment] 2024-11-15 21:49
@taeinkwon hmm, does the toy example run for you?

**Comment by taeinkwon** [comment] 2024-11-15 22:03
Yes, the toy example works, for random numbers in the toy example, it does not converge to the specific numbers. 
Is this repo tested with real images or achieved numbers in the benchmark of the original paper?
It seems like it happens when we have real examples. I used real images and text pairs for the training. FYI, the training code is very similar to the one in the discussion: https://github.com/lucidrains/transfusion-pytorch/discussions/14

**Comment by lucidrains** [comment] 2024-11-15 22:11
@taeinkwon ok gotcha

no I have not confirmed it just yet, like noted in the todo, will be testing with Oxford flowers next

**Comment by lucidrains** [comment] 2024-11-15 22:12
there is also an engineer at Nvidia who is interested in Transfusion and will be working on this soon

**Comment by RefractAI** [comment] 2024-11-15 22:32
I have tried training this using MNIST digits for a few hours, and my observations are:

- The training part looks good, flow loss down to 0.35 after an hour, does significantly denoise the partially noised sample if pred_flow is added to the noised sample.
- Sample transitioning to image decoding does work after a few hundred steps, producing a 1x28x28 image which can be saved.
- BUT the sample images themselves are pure noise, no discernable features

I'd suggest the problem lies in the odeint function.

**Comment by lucidrains** [comment] 2024-11-15 22:39
@RefractAI thank you anon, both for this and your previous QA

I'll get it working, I'm fairly confident it will fly given pi-zero now

**Comment by lucidrains** [comment] 2024-11-16 17:21
@taeinkwon @RefractAI i was able to get image modality only training working this morning, placed in `train_image_only.py` in the root folder

should be able to debug the issue by tomorrow 🤞 thank you for your patience

**Comment by lucidrains** [comment] 2024-11-17 15:16
![5000 0](https://github.com/user-attachments/assets/c3b7a020-5995-40ab-9434-5a5ba329abb2)

@taeinkwon mnist example at 5000 steps, with the language model asking for an image of zero (0)

i think it is fixed

**Closed by lucidrains** 2024-11-17 15:16 UTC
Labels: bug

**Comment by taeinkwon** [comment] 2024-11-18 00:32
Hi @lucidrains , thanks for your update. I checked the new update and the code you provided works. I also tried it with my dataset, and with the current resolution, it works, even with color images. I attached the generated image after 6 epochs. 
![6 500 UNK   UNK  put down chopping board  SEP   PAD   UNK   UNK   UNK   UNK   UNK   UNK   UNK](https://github.com/user-attachments/assets/6b531b12-0f9a-4de6-8815-70fc6c65927e)

However, some parts are still not resolved. I wanted to use the pretrained VAE model like the original TransFusion paper (see the below code), and some parts are not working.
```
vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse")
encoder = vae.encoder
decoder = vae.decoder
model = Transfusion(
        num_text_tokens=vocab_size,
        dim_latent=16,
        modality_default_shape=(( 128,128),),
        modality_encoder = encoder,
        modality_decoder = decoder,
        add_pos_emb = True,
        modality_num_dim = 2,
        transformer = dict(
        dim = 512,
        depth = 8,
    )
    ).cuda()
```

1. It seems like the decoder code does not work. It seems like this code does not call the decoder part for every iteration. The code only calls the decoder function when sampling. Also, I am not sure of the dimensionality when the model is sampling. Shouldn't it follow the dim and dim_latent in the Transfusion class?

2. If I put the end token for text when I train, the code can not sample images anymore. It only samples text. Without the end token, it works like the mnist example.  
```
tokens[tokens==102] = self.tokenizer.vocab_size+1
```

**Comment by lucidrains** [comment] 2024-11-18 02:04
@taeinkwon hi Taein, thank you for confirming the issue is resolved

for 1, unless I misunderstand, why would you require decoder to be called during training? are you not doing latent denoising, in which case only encoder is called during training and decoder called during sampling? (assuming pretrained vae)

for 2, this framework automatically takes care of the start and end text tokens for you. If you insert these manually, sampling will terminate where you place them. I assume you must be placing the end text token before the image in the list

**Comment by lucidrains** [comment] 2024-11-18 02:05
@taeinkwon I have an open issue for VAE, and will get around to an end to end example tomorrow morning, smoothing out any issues in the process

**Comment by taeinkwon** [comment] 2024-11-18 07:56
Hi @lucidrains , thank you for your answer, for 2, now it is clear.

For 1, maybe I don't fully understand the paper, but I thought both VAE encoder and decoder are part of the training. The loss is calculated between the decoded image after latent denoising, isn't it? or at least U-net is part of the training process, which I believe we need to put in the modality_encoder and modality_decoder with the current framework.  (BTW, where can we put U-net, or is it already integrated into the code?)
Maybe I misunderstood it and the optimization only happens in the latent space.

Anyways, the example of the current output is like the following when I put the pretrained encoder and decoder:

![10 3000 UNK  get plate  SEP   PAD   PAD   PAD   PAD   UNK   UNK   UNK   UNK   UNK   UNK](https://github.com/user-attachments/assets/3661e521-b41d-4383-86d2-527ab43c751e)

The output dimensionality is also weird, 2048 x2048. I changed some parts of the code to fit batch inputs as the pretrained VAE (from the diffusers library) accepts batch inputs. My changes are:

Added L1414
modality = rearrange(modality, 'h w (p1 p2 c) -> c (h p1) (w p2)',c=4, p1 = 2, p2 = 2, h = 128)
modality=modality.unsqueeze(0)

Added L1818
modality_tensor = modality_tensor[0]

**Comment by RefractAI** [comment] 2024-11-18 12:52
@taeinkwon Normally the VAE is frozen and not trained. The Transfusion paper doesn't train it. I'm just encoding and decoding using an external VAE myself and using Transfusion only with the pre-encoded latents.

Regarding the Unet up/down, it looks like it's on the todo list, but it's only for patchifying so there's no need for it if you use patch size 1.

**Comment by taeinkwon** [comment] 2024-11-18 13:14
Thanks for the clarification. For VAE, now I understand and will follow another open issue.
The reason why I ask about Unet is that I am also planning to put other modalities (such as audio) and wonder how I can put encoder decoder layers in that case to generate other signals. I probably need to change the code inside in that case?

**Comment by lucidrains** [comment] 2024-11-18 13:42
@taeinkwon hey Taein, yes RefractAI is correct here

however, this discussion has spurred a thought, perhaps i can also involve the decoder with an extra reconstruction loss and perhaps even make it finetuneable. i'll try to incorporate that near end of week once i get the VAE and Unet training examples finished

**Comment by lucidrains** [comment] 2024-11-18 13:45
@taeinkwon for more than one modality, there is [an example](https://github.com/lucidrains/transfusion-pytorch/blob/main/tests/test_transfusion.py#L263) in the tests. i understand Zimmerman's research (and yours by proxy) is still the audio / video self supervised learning

if you had to ask though, it probably means it isn't intuitive enough just yet. i'll work on making it until you are satisfied

**Comment by lucidrains** [comment] 2024-11-18 17:36
@taeinkwon i'll get the unet in there tomorrow morning

**Comment by taeinkwon** [comment] 2024-11-19 18:57
Hi, I also tried to use pretrained VAE (wo u-net) after your update. I trained around 3~4 hours and the result is like the following:

![9 1500 UNK   UNK  pick up bread  SEP   PAD   PAD   PAD   UNK   UNK   UNK   UNK   UNK   UNK   UNK](https://github.com/user-attachments/assets/13791345-9f44-42ee-94c4-88d4a37108d5)

I might need to train longer or debug it to find what the issue is. FYI, I checked the decoder and encoder and it reconstruct image well. (vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse"))

If you have any pointers where I should look at more, that would be helpful. Thanks!

**Comment by lucidrains** [comment] 2024-11-19 19:08
@taeinkwon yea, that looks functional! you'll need to train longer / bigger transformer for sure

**Comment by lucidrains** [comment] 2024-11-19 19:09
@taeinkwon i'll add the ability to fine tune given encoder / decoder on reconstruction loss by end of week

**Comment by lucidrains** [comment] 2024-11-19 20:01
@taeinkwon what is `AutoencoderKL`, is it a huggingface thing?

**Comment by taeinkwon** [comment] 2024-11-19 20:24
https://github.com/huggingface/diffusers/blob/99c0483b67427de467f11aa35d54678fd36a7ea2/src/diffusers/models/autoencoders/autoencoder_kl.py#L262

**Comment by lucidrains** [comment] 2024-11-19 20:26
@taeinkwon thanks! i'll play around with some oxford flowers latent flow matching later this week

**Comment by lucidrains** [comment] 2024-11-20 18:53
@taeinkwon apologies Taein, could you give me one more day? had to refactor a bunch of things to get ready for the unet encoder / decoder

maybe i'll get a second wind this evening and finish it

**Comment by taeinkwon** [comment] 2024-11-22 16:58
One update from my side: my pretrained-VAE does not work even after two days of training. I need to investigate the problem more. Please let me know if you make the pretrained-VAE work for images (I guess Oxford flowers?). Thank you!

**Comment by lucidrains** [comment] 2024-11-22 19:33
@taeinkwon hey Taein, sorry didn't get around to the unet this morning as, was caught up in some experiments of my own (always time consuming)

the VAE is definitely functional given the mnist vae example, but i'll get around to using the pretrained one from stable diffusion for oxford

**Comment by RefractAI** [comment] 2024-11-23 01:41
> One update from my side: my pretrained-VAE does not work even after two days of training. I need to investigate the problem more. Please let me know if you make the pretrained-VAE work for images (I guess Oxford flowers?). Thank you!

Diffusion models take hundreds of epochs to converge. Also, your model may be too small.
If you find an image model that does converge in less time than that, I would be very interested.

**Comment by lucidrains** [comment] 2024-11-24 21:03
hey Taein, finally got the unet functionality completed, and will add an Oxford flowers example tomorrow morning

**Comment by lucidrains** [comment] 2024-11-25 14:28
![13000 1](https://github.com/user-attachments/assets/5257c2e0-37bf-452c-bad0-6b471d5c5054)

`1` at 13k steps with contrived down and upsampling

i'll port in the full resnet blocks from a unet later this week

**Comment by lucidrains** [comment] 2024-11-25 17:51
ran into some issue with the safe tensors package this morning when trying to load the pretrained vae

will try again later this evening

the file i'm working with lives [here](https://github.com/lucidrains/transfusion-pytorch/blob/main/train_latent_only.py)

**Comment by lucidrains** [comment] 2024-11-25 19:17
@taeinkwon hey Taein, finally completed [the script](https://github.com/lucidrains/transfusion-pytorch/commit/4485c28a2b767af84ed390c1291595215dad8fcc) and i'm seeing results within the first 200 steps. do you want to take a look at what i have and see if it makes sense?

**Comment by lucidrains** [comment] 2024-11-25 19:19
![400](https://github.com/user-attachments/assets/2d8247ab-6323-4f1d-822f-428e6d299a03)

400 steps for modality only training

this doesn't rule out an issue with interspersed text training however, i'll get an example in there tomorrow morning using the labels that come with the oxford flower dataset

**Comment by lucidrains** [comment] 2024-11-25 19:52
this is also using an additional reconstruction loss, which I don't have built for the main forward function yet, but will tomorrow

**Comment by taeinkwon** [comment] 2024-11-25 20:08
@lucidrains , thank you for sharing this result. Yes, I tested the code and I can't get a similar quality as I believe I don't have the additional reconstruction loss. I will test it with my dataset once you update it. Thank you!

**Comment by lucidrains** [comment] 2024-11-25 20:10
@taeinkwon could you first try the modality only training to make sure the issue is with the lack of reconstruction loss? I'll expedite getting that in there tomorrow if so (for multimodal forward)

**Comment by taeinkwon** [comment] 2024-11-25 21:01
So when I ran the same code, train_latent_only.py, I got a similar result.

I am also testing a single modality (only images) with the EPIC-KITCHENS dataset, and the results are like the below after 4000 iters.  Maybe because the images are more complicated compared to the flower dataset. I will let the model train for a longer time.

![4_100](https://github.com/user-attachments/assets/17448e3c-efec-4aad-bdae-c436310cdcad)

One question: what is the purpose of L121-123 in the train_latent_only.py? I don't understand these lines.

**Comment by lucidrains** [comment] 2024-11-25 21:04
@taeinkwon yup, i think you just need to leave it on overnight

as for L121-123, that is the logic for gradient accumulation (for bigger effective batch size)

**Comment by lucidrains** [comment] 2024-11-26 13:46
![29100](https://github.com/user-attachments/assets/a8345f0c-ce6a-4bba-ba8c-93a6f7051d19)

~30k steps

this is with only 8k images, batch size 16

more training with more data Taein!

**Comment by taeinkwon** [comment] 2024-11-26 23:28
Hi @lucidrains , the result looks super good! 
What I am trying now is

1. whether the result is still good for another dataset (Epic Kitchens) and 
2. it can learn labels together (Oxford Flower). 

So far (10k), I trained the images and labels together on the Oxford flower dataset and the label does not match.  Have you tried to learn labels together with the image reconstruction? I wonder what the results look like from your side. I will also share my results with another dataset once it is trained. Thank you!

**Comment by lucidrains** [comment] 2024-11-27 16:03
@taeinkwon 
![8300 moon orchid](https://github.com/user-attachments/assets/44ffe950-ab9c-411f-8563-3eadac15bde0)

"moon orchid" at 8.3k steps. i think i can see the orchid kind of?

**Comment by lucidrains** [comment] 2024-11-27 16:23
ok, that one may be a fluke, i'll let it cook for a bit longer

learning a lot about flowers, as i need to google image each label to really know if it is correct 🤣

**Comment by lucidrains** [comment] 2024-11-27 19:56
@taeinkwon so while it isn't perfect yet, at around 30k steps, it starts to get at least the color of the flowers correct

snapdragon

![31800 snapdragon](https://github.com/user-attachments/assets/27c35b91-9e80-4b04-a471-b5acb3705518)

poinsettia

![32100 poinsettia](https://github.com/user-attachments/assets/d8f90128-e24d-4e08-8b18-e8a32bf93a6b)

lotus

![32300 lotus](https://github.com/user-attachments/assets/11b589dd-bc40-4285-b520-30b07b270ce2)

great masterwort (google imaging shows roughly the same color)

![32600 great masterwort](https://github.com/user-attachments/assets/c7a34a15-a6e4-4e6d-a360-393d7d3ebb1d)

i'm sure with more training and data it would perform even better. ok i'm stopping the run early

**Comment by RefractAI** [comment] 2024-12-02 15:34
https://arxiv.org/abs/2411.19722
Thought I'd highlight an interesting new text-image transformer paper, "Jetformer" from Deepmind. Takes an autoregressive approach with normalizing flows.

**Comment by lucidrains** [comment] 2024-12-02 17:56
@RefractAI nice, i don't know if i believe in normalizing flows anymore, but i'll queue up the paper for future reading, thanks!

**Comment by lucidrains** [comment] 2024-12-02 19:41
@RefractAI ahh, paper looks quite good actually, will read it this week :+1:

**Comment by lucidrains** [comment] 2024-12-03 23:15
@RefractAI may pass on it, as the images in the appendix do not look that great. you can see lack of global coherence here and there, and the lemurs have a weird saturated color

**Comment by lucidrains** [comment] 2024-12-04 14:39
@RefractAI think i will pass on the jetformer paper. bidirectional attention is still the way to go for modalities and that is where Transfusion shines

**Comment by RefractAI** [comment] 2024-12-04 15:28
> the most interesting part of their paper may end up being the noise curriculum

Yes, the noise curriculum part could be used for diffusion or flow too as it's just an augmentation.

**Comment by lucidrains** [comment] 2024-12-04 15:31
@RefractAI curriculum learning is just underused in neural network training in general

**Comment by Benjamin-Sor** [comment] 2026-06-17 02:56
@taeinkwon 
Would you mind sharing your training recipe for generating images from Epic Kitchens? I'm curious how good you were able to reproduce the images in the end.

Likewise to @lucidrains. How good were you able to get the flowers?
